const chai = require('chai');
chai.config.truncateThreshold = 0;
const { expect } = chai;
const BankingSystem = require('../bankingSystem');

/**
 * The test class below can be considered as a playground - feel free to modify it as you need, e.g.:
 * - add your own custom tests
 * - delete existing tests
 * - modify test contents or expected output
 *
 * The results of tests from this file will always be at the beginning of the report generated by clicking the "Run" button.
 *
 * The results of these tests do not affect the final score (unless the project fails to build).
 */
describe('Sandbox tests', () => {

    let system;

    beforeEach(() => {
        system = new BankingSystem();
    });

    it('Test sample', function () {
        this.timeout(400);
        expect(system.createAccount(1, 'account1')).to.be.true;
        expect(system.createAccount(2, 'account2')).to.be.true;
        expect(system.deposit(3, 'account1', 2000)).to.deep.equal(2000);
        expect(system.deposit(4, 'account2', 1000)).to.deep.equal(1000);
        expect(system.transfer(5, 'account1', 'account2', 500)).to.deep.equal(1500);
    });
});
